### ISSUE TITLE
Kijk eens naar hasManyThrough

### ISSUE THREAD

**Issue by gglerum** [DOBronk/laravel#9]
https://github.com/DOBronk/laravel/blob/dd9ec3f721b46c2ea03ccf04f4aca7d79599865d/studentmanager/app/Models/User.php#L86-L95

Kan veel makkelijker met [hasManyThrough](https://laravel.com/docs/11.x/eloquent-relationships#has-many-through)

**Comment by DOBronk** [comment]
Laravel support dit niet standaard wanneer de intermediate table een pivot table is. Op deze manier moet ik een speciaal model aanmaken zoals ik ook bij roles heb gedaan (roles model voor de werkelijke tabel, role model voor de pivot table koppeling).

Maar het kan wel makkelijker inderdaad, ik zal het eens met een intermediate model implementeren.

[https://codecourse.com/articles/laravel-has-many-through-pivot-relationships](https://codecourse.com/articles/laravel-has-many-through-pivot-relationships)

**Comment by DOBronk** [comment]
Uiteindelijk bleek het nog iets complexer en heb ik de query zelf maar opgebouwt via QueryBuilder en gekoppeld via newHasMany. hasManyThrough werkt hier in ieder geval niet.

```php
    public function mentors(): HasMany
    {
        $instance = new ClassroomUser();

        return $this->newHasMany($instance->newQuery()->selectRaw("classroom_user.*, users.*")
            ->from('classroom_user')
            ->join('classrooms', 'classroom_user.classroom_id', '=', 'classrooms.id')
            ->join('users', 'users.id', '=', 'classrooms.mentor_id'), $this, 'user_id', $this->getKeyName());
    }
```
